version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@mysql_db:3306/dev.db
      - JWT_SECRET_KEY=your_secret_key
    volumes:
      - .:/app
