version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql:///prod_db
      - JWT_SECRET_KEY=your_secret_key
    volumes:
      - .:/app
